# Generated by Django 5.0.5 on 2024-05-07 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('memo', models.TextField(blank=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('due_time', models.DateTimeField()),
                ('complete_time', models.DateTimeField(null=True)),
                ('is_important', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
